#spring:
#  application:
#    name: system-service
#
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        namespace: dev
#        group: xuecheng-plus-project
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.233.131:3306/xcplus_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
#    username: root
#    password: root
# 日志文件配置路径



